Supervised Learning

Linear Regression

In [109]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [110]:
data=pd.read_csv("Boston.csv")

In [111]:
data.head()

,crim,zn,indus,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [112]:
x=data.iloc[:,:12].values
y=data.iloc[:,12].values

In [78]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [79]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [80]:
model.coef_

array([-1.25156811e-01,  4.48575121e-02,  2.01265385e-02, -1.62895522e+01,
        3.77366409e+00, -2.13185120e-03, -1.40611846e+00,  2.66835482e-01,
       -1.21692284e-02, -1.07660161e+00,  8.72533635e-03, -4.94425348e-01])

In [81]:
model.intercept_

np.float64(38.42706211257687)

In [82]:
model.score(x_train,y_train)

0.7690953567794605

In [83]:
model.score(x_train,y_train)*100

76.90953567794605

In [84]:
y_pred=model.predict(x_test)

In [85]:
MSE=mean_squared_error(y_pred,y_test)

In [86]:
MSE

34.21225254753343

In [87]:
RMSE=np.sqrt(MSE)
RMSE

np.float64(5.849124083786685)

In [88]:
x1=np.array([[0.00732,16.0,2.31,0.598,8.575,65.2,4.0800,1,236,17.3,396.90,4.98],[0.00932,12.0,3.31,0.498,6.575,67.2,5.0800,1,266,15.3,396.90,4.98
]])

In [89]:
model.predict(x1)

array([35.70295324, 30.00277067])

In [90]:
x2=np.array([0.00732,16.0,2.31,0.598,8.575,65.2,4.0800,1,236,17.3,396.90,4.98]).reshape(1,12)

In [91]:
model.predict(x2)

array([35.70295324])

Categorical Independent Variables

In [92]:
data=pd.read_csv("GPA_data.CSV")

In [93]:
data.head()

,ID,Gender,Age,Extra_Curricular,Study_Hours,Annual_Income,Distance_From_Home,GPA
0,8867,Male,22,Societies,10,1318792,154,1.76
1,1316,Female,24,Societies,9,874657,181,3.88
2,9443,Male,22,Societies,15,1098331,94,1.73
3,1829,Female,25,No,9,1680585,8,1.29
4,1989,Male,26,No,7,1361560,122,3.19

In [94]:
df_dum=pd.get_dummies(data[["Gender","Extra_Curricular"]])
df_dum

,Gender_Female,Gender_Male,Extra_Curricular_No,Extra_Curricular_Societies,Extra_Curricular_Sports
0,False,True,False,True,False
1,True,False,False,True,False
2,False,True,False,True,False
3,True,False,True,False,False
4,False,True,True,False,False
...,...,...,...,...,...
995,True,False,True,False,False
996,False,True,True,False,False
997,False,True,False,False,True
998,False,True,False,True,False
999,False,True,True,False,False

In [95]:
df_dum.drop(["Gender_Female","Extra_Curricular_No"],axis=1,inplace=True)
df_dum

     Gender_Male  Extra_Curricular_Societies  Extra_Curricular_Sports
0           True                        True                    False
1          False                        True                    False
2           True                        True                    False
3          False                       False                    False
4           True                       False                    False
..           ...                         ...                      ...
995        False                       False                    False
996         True                       False                    False
997         True                       False                     True
998         True                        True                    False
999         True                       False                    False

[1000 rows x 3 columns]

In [96]:
data_new=pd.concat([data,df_dum],axis=1)
data_new.head()

,ID,Gender,Age,Extra_Curricular,Study_Hours,Annual_Income,Distance_From_Home,GPA,Gender_Male,Extra_Curricular_Societies,Extra_Curricular_Sports
0,8867,Male,22,Societies,10,1318792,154,1.76,True,True,False
1,1316,Female,24,Societies,9,874657,181,3.88,False,True,False
2,9443,Male,22,Societies,15,1098331,94,1.73,True,True,False
3,1829,Female,25,No,9,1680585,8,1.29,False,False,False
4,1989,Male,26,No,7,1361560,122,3.19,True,False,False

In [97]:
data_new.drop(["ID","Gender","Extra_Curricular"],axis=1,inplace=True)
data_new.head()

,Age,Study_Hours,Annual_Income,Distance_From_Home,GPA,Gender_Male,Extra_Curricular_Societies,Extra_Curricular_Sports
0,22,10,1318792,154,1.76,True,True,False
1,24,9,874657,181,3.88,False,True,False
2,22,15,1098331,94,1.73,True,True,False
3,25,9,1680585,8,1.29,False,False,False
4,26,7,1361560,122,3.19,True,False,False

Cross Validation Approach

In [98]:
from sklearn.model_selection import cross_val_score

In [99]:
ncvals=cross_val_score(model,x_train,y_train,cv=10,scoring='neg_mean_squared_error')
ncvals

array([-15.1507166 , -16.21354133, -19.8720515 , -22.20787221,
       -18.23202084, -19.26308788, -38.81641962, -30.28243052,
       -22.54464364, -11.89223922])

In [100]:
cvals=-ncvals
cvals

array([15.1507166 , 16.21354133, 19.8720515 , 22.20787221, 18.23202084,
       19.26308788, 38.81641962, 30.28243052, 22.54464364, 11.89223922])

In [101]:
np.sqrt(cvals)

array([3.89239214, 4.02660419, 4.45780793, 4.71252291, 4.26989705,
       4.38897344, 6.23028247, 5.50294744, 4.74812001, 3.44851261])

In [102]:
np.mean(np.sqrt(cvals))

np.float64(4.567806020036128)

Recursive Feature Elimination

In [141]:
from sklearn.feature_selection import RFE,RFECV

In [104]:
rfe=RFE(estimator=LinearRegression(),n_features_to_select=7)

In [105]:
elm_fit=rfe.fit(x_train,y_train)

In [106]:
elm_fit.n_features_

np.int64(7)

In [107]:
elm_fit.support_

array([ True, False, False,  True,  True, False,  True,  True, False,
        True, False,  True])

In [132]:
df_x=data.iloc[:,:12]
df_y=data.iloc[:,12]

In [133]:
df_x.columns

Index(['crim', 'zn', 'indus', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat'],
      dtype='str')

In [134]:
selected=df_x.columns[elm_fit.support_]
selected

Index(['crim', 'nox', 'rm', 'dis', 'rad', 'ptratio', 'lstat'], dtype='str')

In [135]:
df_x.head()

,crim,zn,indus,nox,rm,age,dis,rad,tax,ptratio,black,lstat
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33

In [136]:
df_x1=df_x[selected]
df_x1.head()

      crim    nox     rm     dis  rad  ptratio  lstat
0  0.00632  0.538  6.575  4.0900    1     15.3   4.98
1  0.02731  0.469  6.421  4.9671    2     17.8   9.14
2  0.02729  0.469  7.185  4.9671    2     17.8   4.03
3  0.03237  0.458  6.998  6.0622    3     18.7   2.94
4  0.06905  0.458  7.147  6.0622    3     18.7   5.33

In [137]:
elm_fit.ranking_

array([1, 3, 2, 1, 1, 6, 1, 1, 4, 1, 5, 1])

In [138]:
x=df_x.values
y=df_y.values

In [139]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]], shape=(506, 12))

In [140]:
x1=rfe.fit_transform(x_train,y_train)
x1

array([[ 0.35809,  0.507  ,  6.951  , ...,  8.     , 17.4    ,  9.71   ],
       [ 0.15876,  0.413  ,  5.961  , ...,  4.     , 19.2    ,  9.88   ],
       [ 0.11329,  0.428  ,  6.897  , ...,  6.     , 16.6    , 11.38   ],
       ...,
       [ 0.15098,  0.547  ,  6.021  , ...,  6.     , 17.8    , 10.3    ],
       [ 0.22927,  0.448  ,  6.03   , ...,  3.     , 17.9    , 18.8    ],
       [ 0.13914,  0.51   ,  5.572  , ...,  5.     , 16.6    , 14.69   ]],
      shape=(404, 7))

In [142]:
rfecv=RFECV(estimator=LinearRegression(),min_features_to_select=1,cv=10)

In [143]:
rfecv.fit(x_train,y_train)

RFECV(cv=10, estimator=LinearRegression())

In [144]:
rfecv.n_features_

np.int64(11)

In [145]:
df_x.columns[rfecv.support_]

Index(['crim', 'zn', 'indus', 'nox', 'rm', 'dis', 'rad', 'tax', 'ptratio',
       'black', 'lstat'],
      dtype='str')

In [148]:
x2=rfecv.fit_transform(x_train,y_train)
x2

array([[3.5809e-01, 0.0000e+00, 6.2000e+00, ..., 1.7400e+01, 3.9170e+02,
        9.7100e+00],
       [1.5876e-01, 0.0000e+00, 1.0810e+01, ..., 1.9200e+01, 3.7694e+02,
        9.8800e+00],
       [1.1329e-01, 3.0000e+01, 4.9300e+00, ..., 1.6600e+01, 3.9125e+02,
        1.1380e+01],
       ...,
       [1.5098e-01, 0.0000e+00, 1.0010e+01, ..., 1.7800e+01, 3.9451e+02,
        1.0300e+01],
       [2.2927e-01, 0.0000e+00, 6.9100e+00, ..., 1.7900e+01, 3.9274e+02,
        1.8800e+01],
       [1.3914e-01, 0.0000e+00, 4.0500e+00, ..., 1.6600e+01, 3.9690e+02,
        1.4690e+01]], shape=(404, 11))